---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-byte-order-marker
      - id: check-builtin-literals
        exclude: test_data/.*$
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
        exclude: test_data/.*$
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        exclude: test_data/.*$
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: importanize
        name: importanize
        entry: python -m importanize
        language: python
        language_version: python3
        types: [python]
        args: [-v, --no-subconfig]
        additional_dependencies: [click, pluggy, pyflakes]
        exclude: test_data/.*$

  - repo: https://github.com/python/black
    rev: 'master'
    hooks:
      - id: black
        args: [--line-length=88, --safe]
        language_version: python3
        exclude: test_data/.*$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'master'
    hooks:
      - id: mypy
        language_version: python3
        args: []
        exclude: test_data/.*$

  - repo: https://github.com/mgedmin/check-manifest
    rev: 'master'
    hooks:
      - id: check-manifest

  - repo: https://github.com/miki725/pre-commit-twine-check
    rev: 'master'
    hooks:
      - id: twine-check
